### PR TITLE
Constraint variants parametrised

### PR DESCRIPTION
**Pull request by dourouc05**
Proposed solution to #22.

Would you agree with this PR? Do you have other ideas to solve the same issue? This is mostly a fully fleshed-out version of what I presented in #22, but with enumerations instead of Booleans for legibility. Documentation is not yet up to date. 

@Azzaare @odow

### CODE REVIEW

**Comment by odow** [comment]
I don't have a better suggestion for now :(

**Comment by Azzaare** [comment]
I don't have better idea either.

I guess I will have to interface it for some solvers and see if other ideas come.

Thanks!

**Comment by dourouc05** [comment]
Shall I merge it (once the tests pass, that is), tag a new version, and we'll see later?

**Comment by Azzaare** [comment]
CI passed :v: 

I think you merge indeed. Maybe tag breaking changes version?

**Comment by dourouc05** [comment]
That's why I tagged 0.3.2 just before :)! I will do the same kind of refactoring for other sets with many variants and then tag a 0.4.0.

**Pull request merged**
