### PR TITLE
Update to MOI v1

### PR DESCRIPTION
**Pull request by blegat**
`MOI.DeprecatedTest` was removed so we need to remove `ConstraintProgrammingExtensions.DeprecatedTest` as well. It has already been udated to `ConstraintProgrammingExtensions.Test` which uses the new `MOI.Test` so  it seems safe to remove.
This is going to be breaking but the `Project.toml` already has `v0.7.0` set and not released so we can do `v0.7`

### CODE REVIEW

**Review by dourouc05 — APPROVED** [review]
Looks good to me!

**Comment by Azzaare** [comment]
I need to make better teams and related privileges. The tests should run now. Unless it is broken we can merge.

**Comment by Azzaare** [comment]
I'm going to update the test config to cover a bit more (if you don't mind) and then merge it if it still passes

EDIT: force pushes came from me squashing many CI fixes for a cleaner history, sorry

**Comment by Azzaare** [comment]
Tests are failing on x86. Is there a specific reason to not test against x86 (beside the fact that it will be a bit annoying to update all the tests to handle it ^^)?
@dourouc05 I think you are the main contributor to those tests, what do you think? I am trying to fix the error on #34, but maybe it is not worth the time (or we have some code incompatible with x86?)

EDIT: Small tests on #34 
```
┌ Warning: Debug type
│   typeof(t.output_index) = Int64
│   typeof(i) = Int32
│   typeof(t.scalar_term.coefficient) = Int32
│   typeof(one(T)) = Int32
└ @ Main ~/work/ConstraintProgrammingExtensions.jl/ConstraintProgrammingExtensions.jl/test/Bridges/Constraint/NonOverlappingOrthotopes/noov_to_noovcond.jl:110
New constraint: Test Failed at /home/runner/work/ConstraintProgrammingExtensions.jl/ConstraintProgrammingExtensions.jl/test/Bridges/Constraint/NonOverlappingOrthotopes/noov_to_noovcond.jl:111
  Expression: t.output_index === i
   Evaluated: 1 === 1
Stacktrace:
 [1] macro expansion
   @ ~/work/ConstraintProgrammingExtensions.jl/ConstraintProgrammingExtensions.jl/test/Bridges/Constraint/NonOverlappingOrthotopes/noov_to_noovcond.jl:111 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/work/ConstraintProgrammingExtensions.jl/ConstraintProgrammingExtensions.jl/test/Bridges/Constraint/NonOverlappingOrthotopes/noov_to_noovcond.jl:104 [inlined]
 [4] top-level scope
   @ /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1226
   ```
   
   So we have an Int32 vs. Int64 issue here
   
   
   EDIT2:
   
   We can still merge anyway. Is there any built in word size (64 bits) in MOI or CPE? In particular, for Int.
   If it is only an issue with the tests, we should probably update them.

**Comment by blegat** [comment]
It seems fair to simply update the tests from `===` to `==`. Using `===` doesn't achieve anything and it will make 32-bit fail because we explicitly chose to use `Int64` in MOI so that there are no differences between 64-bit and 32-bit.

**Comment by Azzaare** [comment]
> It seems fair to simply update the tests from `===` to `==`. Using `===` doesn't achieve anything and it will make 32-bit fail because we explicitly chose to use `Int64` in MOI so that there are no differences between 64-bit and 32-bit.

I was hoping for that. But my knowledge of MOI is low, so I did not want to break everything. 

I will update tomorrow. Thanks

**Comment by dourouc05** [comment]
@Azzaare I believe the reason of the `===` was to ensure that the values were integers and not floats. But it's been a while… Since then, MOI made great progress in supporting other types than `Float64`.

Another question: what is the value of supporting x86? These tests for so many platforms take a while to run…

**Comment by Azzaare** [comment]
Running the test for x86 is more for the sake of ensuring that the package is compatible with this architecture, if it is the case.

As a matter of fact, I do run distributed solvers, and some machines are x86. It is not critical as I can always find a way around, but it is more convenient if I can keep compatibility for MOI/JuMP.

We can just keep a small part of the test set for x86 if you feel like it is taking too long (I don't mind much either way).

Thank you for the answer.

**Pull request merged**
